application:
  index:
    info: hello-service

server:
  port: 8090

## eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  # 更改服务实例ID，默认显示格式 机器名:实例名:端口
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}-${spring.application.name}:@project.version@

## spring
spring:
  application:
    name: hello-service
