application:
  index:
    info: hello-service

server:
  port: 9000

## eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 8080

## spring
spring:
  application:
    name: world-service
