application:
  index:
    info: hello-service

server:
  port: 9000

## eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

## spring
spring:
  application:
    name: world-service
